// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSfR6FH_-JwXuHpTri_1eQURLzDWaC2ZU',
    appId: '1:152837607614:android:9ce9d6635b884eb1094eef',
    messagingSenderId: '152837607614',
    projectId: 'chitchat-79eb8',
    storageBucket: 'chitchat-79eb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY6W84T_tFxn3K51MksXl_aQm7rP5ldlE',
    appId: '1:152837607614:ios:8a059e648cb891fb094eef',
    messagingSenderId: '152837607614',
    projectId: 'chitchat-79eb8',
    storageBucket: 'chitchat-79eb8.appspot.com',
    androidClientId: '152837607614-ib1sbhkd4ko55s9e0cdjkeopjqo0ucpo.apps.googleusercontent.com',
    iosClientId: '152837607614-94ojvdpfm9lkrqr0b3kuk0ovtv8l56ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.chapapp',
  );

}